version: "3.8"

services:
  nuxt3-debit:
    image: phanlyhuynh/node:18-alpine3.16
    container_name: debit-fe
    restart: always
    ports:
      - 3000:3000
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app